### ISSUE TITLE
E_NOTICE - Undefined index: approved

### ISSUE THREAD

**Issue by spin0us** [AizkibelRojo/grav-bettercomments#10]
The error is still there.

![Capture](https://user-images.githubusercontent.com/1810807/194066876-717fb6ca-6dff-4e92-8013-7a8b13847dd1.PNG)

Versions
* Grav v1.7.36
* Admin v1.10.36
* PHP Version 7.4.30
* Apache/2.4.54 (Debian)
* Better comments 1.0.7

 ```
[2022-10-05 14:57:32] grav.CRITICAL: Undefined index: approved - Trace:
    #0 /var/www/xxxxx/system/src/Grav/Common/Debugger.php(843): Whoops\Run->handleError()
    #1 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(701): Grav\Common\Debugger->deprecatedErrorHandler() 
    #2 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(455): Grav\Plugin\BetterCommentsPlugin->fetchComments() 
    #3 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\BetterCommentsPlugin->onTwigSiteVariables() 
    #4 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() 
    #5 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() 
    #6 /var/www/xxxxx/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() 
    #7 /var/www/xxxxx/system/src/Grav/Common/Twig/Twig.php(413): Grav\Common\Grav->fireEvent() 
    #8 /var/www/xxxxx/system/src/Grav/Common/Service/OutputServiceProvider.php(36): Grav\Common\Twig\Twig->processSite() 
    #9 /var/www/xxxxx/vendor/pimple/pimple/src/Pimple/Container.php(122): Grav\Common\Service\OutputServiceProvider->Grav\Common\Service\{closure}() 
    #10 /var/www/xxxxx/system/src/Grav/Common/Processors/RenderProcessor.php(40): Pimple\Container->offsetGet() 
    #11 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RenderProcessor->process() 
    #12 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #13 /var/www/xxxxx/system/src/Grav/Common/Processors/DebuggerAssetsProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #14 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\DebuggerAssetsProcessor->process() 
    #15 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #16 /var/www/xxxxx/system/src/Grav/Common/Processors/PagesProcessor.php(112): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #17 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process() 
    #18 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #19 /var/www/xxxxx/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #20 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process() 
    #21 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #22 /var/www/xxxxx/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #23 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process() 
    #24 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #25 /var/www/xxxxx/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle()
    #26 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process() 
    #27 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #28 /var/www/xxxxx/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #29 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process() 
    #30 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #31 /var/www/xxxxx/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #32 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process() 
    #33 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle()
    #34 /var/www/xxxxx/system/src/Grav/Common/Processors/RequestProcessor.php(64): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #35 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process() 
    #36 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #37 /var/www/xxxxx/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #38 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process() 
    #39 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #40 /var/www/xxxxx/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #41 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() 
    #42 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #43 /var/www/xxxxx/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #44 /var/www/xxxxx/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() 
    #45 /var/www/xxxxx/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile() 
    #46 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() 
    #47 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #48 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #49 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() 
    #50 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #51 /var/www/xxxxx/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() #52 /var/www/xxxxx/index.php(47): Grav\Common\Grav->process() 
    #53 {main} [] []
```

**Comment by spin0us** [comment]
Problem occurs on several lines
* 650
* 701
* 727

**Comment by AizkibelRojo** [comment]
@spin0us 
Can you dowload this version (https://github.com/AizkibelRojo/grav-bettercomments/archive/refs/heads/bugfix/undefined-array-key-approved.zip) and say if problems has dissapear, I use if whit count to solve this, if you have 0 comments the lines wont be executed.

If you have comments and this error persist, it posible you need to execute permission fix scrtip for Grav CMS.

If it results satisfactory bugfix I will release new version as soon as posible. 


Thanks for your time and info.

**Comment by spin0us** [comment]
No, it's not working, still an error on line 701.
Here is the patch that work for line 701
```
if (isset($comment['approved']) && (int)$comment['approved'] !== 2 && (int)$comment['answer'] === 0) {
```
and 704
```
if (isset($comment['approved']) && (int)$comment['approved'] !== 2 && (int)$comment['answer'] !== 0) {
```

**Comment by AizkibelRojo** [comment]
I will use your code, thanks for your fix and time @spin0us

**Comment by spin0us** [comment]
And there's still an error on line 650 and 728 too.

**Comment by spin0us** [comment]
Here is my working version [bettercomments.zip](https://github.com/AizkibelRojo/grav-bettercomments/files/9717076/bettercomments.zip)

Everything seems to work, except for the answer system. When validating a comment answer in the admin panel, the POST request is sent but does not seem to be processed. Need a new issue?

**Comment by AizkibelRojo** [comment]
Open issue if you have problemns in new version, I try to fix problem caused by the change of behabiour for admin page

**Comment by AizkibelRojo** [comment]
Issue solved, thanks to @spin0us
