### ISSUE TITLE
Class 'Grav\Plugin\BetterCommentsPlugin' does not have a method 'onFormProcessed'

### ISSUE THREAD

**Issue by codesalatdev** [AizkibelRojo/grav-bettercomments#3]
Hi there,

I have seen #1 and #2 and I am already using version 1.0.3 of your plugin. It has the exact features I've been expecting from the original comments plugin, but when trying to submit a comment, the error in the title occures.

In my templates, I have embedded the plugin with a conditional load already, so the plugin *is* active and the route is configured correctly (in fact, I didn't need to change anything on it).

There seems to be something different going on (?)

Edit: Log
```
[2022-08-15 00:23:19] grav.CRITICAL: Failed to create closure from callable: class 'Grav\Plugin\BetterCommentsPlugin' does not have a method 'onFormProcessed' - Trace: #0 /var/www/codesalat/vendor/symfony/event-dispatcher/EventDispatcher.php(307): Closure::fromCallable() #1 /var/www/codesalat/vendor/symfony/event-dispatcher/EventDispatcher.php(67): Symfony\Component\EventDispatcher\EventDispatcher->optimizeListeners() #2 /var/www/codesalat/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #3 /var/www/codesalat/user/plugins/form/classes/Form.php(940): Grav\Common\Grav->fireEvent() #4 /var/www/codesalat/user/plugins/form/form.php(274): Grav\Plugin\Form\Form->post() #5 /var/www/codesalat/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\FormPlugin->onPageInitialized() #6 /var/www/codesalat/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() #7 /var/www/codesalat/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() #8 /var/www/codesalat/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() #9 /var/www/codesalat/system/src/Grav/Common/Processors/PagesProcessor.php(59): Grav\Common\Grav->fireEvent() #10 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PagesProcessor->process() #11 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #12 /var/www/codesalat/system/src/Grav/Common/Processors/TwigProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() #13 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TwigProcessor->process() #14 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #15 /var/www/codesalat/system/src/Grav/Common/Processors/AssetsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #16 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\AssetsProcessor->process() #17 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #18 /var/www/codesalat/system/src/Grav/Common/Processors/SchedulerProcessor.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #19 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\SchedulerProcessor->process() #20 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #21 /var/www/codesalat/system/src/Grav/Common/Processors/BackupsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #22 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\BackupsProcessor->process() #23 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #24 /var/www/codesalat/system/src/Grav/Common/Processors/TasksProcessor.php(69): Grav\Framework\RequestHandler\RequestHandler->handle() #25 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\TasksProcessor->process() #26 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #27 /var/www/codesalat/system/src/Grav/Common/Processors/RequestProcessor.php(64): Grav\Framework\RequestHandler\RequestHandler->handle() #28 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\RequestProcessor->process() #29 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #30 /var/www/codesalat/system/src/Grav/Common/Processors/ThemesProcessor.php(38): Grav\Framework\RequestHandler\RequestHandler->handle() #31 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\ThemesProcessor->process() #32 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #33 /var/www/codesalat/system/src/Grav/Common/Processors/PluginsProcessor.php(39): Grav\Framework\RequestHandler\RequestHandler->handle() #34 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() #35 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #36 /var/www/codesalat/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() #37 /var/www/codesalat/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() #38 /var/www/codesalat/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile() #39 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() #40 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #41 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() #42 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() #43 /var/www/codesalat/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() #44 /var/www/codesalat/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() #45 /var/www/codesalat/index.php(47): Grav\Common\Grav->process() #46 {main} [] []
```

**Comment by AizkibelRojo** [comment]
@codesalatdev Please, can you say me what template are you using?
I want to reproduce issue and fix it

**Comment by codesalatdev** [comment]
> @codesalatdev Please, can you say me what template are you using? I want to reproduce issue and fix it

Sure, I am currently using [Landed](https://github.com/hughbris/grav-theme-landed) and used the base template to build a blog post template. My additions are pretty simple and don't contain any plugin logic, so if the issue lies within the theme it should be in there.

**Comment by AizkibelRojo** [comment]
@codesalatdev Reweing code I have see te error, plugin was configured to use "onFormProcessed" hook from grav but realli when it works via AJAX it was removed, that was causing the error.

Pluging is updated, this will solve the problem, please say if it work or needs more workaround.

Thanks for all

**Comment by codesalatdev** [comment]
@AizkibelRojo hmm, the error is gone, but now the comments just don't appear anywhere (neither on the site nor in the admin panel). There is also no directory under `user/data/comments`; I still got the mail that there should be a new comment tho.

**Comment by AizkibelRojo** [comment]
@codesalatdev can you use this prerelease https://github.com/AizkibelRojo/grav-bettercomments/releases/tag/beta1.0.5 and give my feedback i have fixed few errors.

When you send a comment it well see on FF console as HRX request like this:

![Captura de Pantalla 2022-08-16 a las 13 02 21](https://user-images.githubusercontent.com/99652175/184864397-38812d1f-3c6f-4758-9128-a7214822863d.png)

**Comment by AizkibelRojo** [comment]
New version released
