### ISSUE TITLE
E_WARNING - Undefined array key "approved"

### ISSUE THREAD

**Issue by layer07** [AizkibelRojo/grav-bettercomments#8]
After installing it immediately throws me that error.
![Warning](https://user-images.githubusercontent.com/34219623/193709722-6e5ac846-b2ad-43df-b039-884e0d2e194f.png)

**Comment by AizkibelRojo** [comment]
hi @layer07 can yo sare your log files please.

**Comment by spin0us** [comment]
I just got the same problem. Here is my log :
```
[2022-10-04 16:55:36] grav.CRITICAL: Undefined index: approved - Trace:
    #0 /var/www/xxxxx/system/src/Grav/Common/Debugger.php(843): Whoops\Run->handleError() 
    #1 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(650): Grav\Common\Debugger->deprecatedErrorHandler() 
    #2 [internal function]: Grav\Plugin\BetterCommentsPlugin->Grav\Plugin\{closure}() 
    #3 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(651): array_filter() 
    #4 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(556): Grav\Plugin\BetterCommentsPlugin->getLastComments() 
    #5 /var/www/xxxxx/user/plugins/bettercomments/bettercomments.php(572): Grav\Plugin\BetterCommentsPlugin->initializeAdmin() 
    #6 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(264): Grav\Plugin\BetterCommentsPlugin->onPluginsInitialized() 
    #7 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(239): Symfony\Component\EventDispatcher\EventDispatcher->doDispatch() 
    #8 /var/www/xxxxx/vendor/symfony/event-dispatcher/EventDispatcher.php(73): Symfony\Component\EventDispatcher\EventDispatcher->callListeners() 
    #9 /var/www/xxxxx/system/src/Grav/Common/Grav.php(597): Symfony\Component\EventDispatcher\EventDispatcher->dispatch() 
    #10 /var/www/xxxxx/system/src/Grav/Common/Processors/PluginsProcessor.php(36): Grav\Common\Grav->fireEvent() 
    #11 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\PluginsProcessor->process() 
    #12 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #13 /var/www/xxxxx/system/src/Grav/Common/Processors/InitializeProcessor.php(130): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #14 /var/www/xxxxx/system/src/Grav/Common/Debugger.php(546): Grav\Common\Processors\InitializeProcessor::Grav\Common\Processors\{closure}() 
    #15 /var/www/xxxxx/system/src/Grav/Common/Processors/InitializeProcessor.php(131): Grav\Common\Debugger->profile() 
    #16 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Common\Processors\InitializeProcessor->process() 
    #17 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #18 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Middlewares/MultipartRequestSupport.php(40): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #19 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(50): Grav\Framework\RequestHandler\Middlewares\MultipartRequestSupport->process() 
    #20 /var/www/xxxxx/system/src/Grav/Framework/RequestHandler/Traits/RequestHandlerTrait.php(62): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #21 /var/www/xxxxx/system/src/Grav/Common/Grav.php(312): Grav\Framework\RequestHandler\RequestHandler->handle() 
    #22 /var/www/xxxxx/index.php(47): Grav\Common\Grav->process() 
    #23 {main} [] []
```

**Comment by AizkibelRojo** [comment]
I think the problem is solved, new release has been launched if you have any problem please open new issue whit all data posible to reproduce the error like PHP version.

Thanks for report @layer07 @spin0us
